-- Drop existing tables if they exist
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS locations;

-- Create locations table with simplified info field
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    coordinates NUMERIC[] NOT NULL,
    info JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Create tasks table with updated structure
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
    info TEXT NOT NULL,
    date_added TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_completed TIMESTAMP WITH TIME ZONE,
    tries INTEGER DEFAULT 0
);

-- Insert sample data
INSERT INTO locations (name, coordinates, info)
VALUES
(
    'Rose Garden',
    ARRAY[13.268969332277585, 57.47291624111792],
    '{
        "text": "A beautiful rose garden that requires regular care throughout the growing season. Regular watering and pruning needed.",
        "images": [
            {
                "url": "https://example.com/roses1.jpg",
                "caption": "Spring blooms"
            }
        ]
    }'
),
(
    'Vegetable Patch',
    ARRAY[13.270514892277585, 57.47191624111792],
    '{
        "text": "Organic vegetable garden with rotating crops. Needs regular weeding and monitoring.",
        "images": []
    }'
),
(
    'Herb Garden',
    ARRAY[13.267423772277585, 57.47391624111792],
    '{
        "text": "Mediterranean herb garden with culinary and medicinal herbs. Most herbs prefer well-draining soil.",
        "images": []
    }'
);

-- Insert sample tasks
INSERT INTO tasks (location_id, info, date_added, tries)
SELECT
    l.id,
    'Remove dead wood and shape bushes\nSpring pruning maintenance for the rose garden',
    NOW() - INTERVAL '2 days',
    0
FROM locations l
WHERE l.name = 'Rose Garden';

INSERT INTO tasks (location_id, info, date_added, date_completed, tries)
SELECT
    l.id,
    'Apply balanced rose fertilizer\nUse organic fertilizer for better results',
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '1 day',
    1
FROM locations l
WHERE l.name = 'Rose Garden';

INSERT INTO tasks (location_id, info, date_added, tries)
SELECT
    l.id,
    'Plant tomato seedlings\nMaintain proper spacing between plants for optimal growth',
    NOW() - INTERVAL '1 day',
    2
FROM locations l
WHERE l.name = 'Vegetable Patch';

INSERT INTO tasks (location_id, info, date_added, tries)
SELECT
    l.id,
    'Harvest basil before flowering\nBest flavor when harvested in the morning',
    NOW(),
    0
FROM locations l
WHERE l.name = 'Herb Garden';
