-- Drop existing tables if they exist
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS locations;

-- Create locations table with rich text info field
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    coordinates NUMERIC[] NOT NULL,
    info TEXT NOT NULL DEFAULT ''
);

-- Create tasks table with updated structure
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
    info TEXT NOT NULL,
    date_to_start TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_completed TIMESTAMP WITH TIME ZONE,
    completion_status TEXT CHECK (completion_status IN ('done', 'postponed', 'canceled')),
    tries INTEGER DEFAULT 0
);

-- Insert sample data
INSERT INTO locations (name, coordinates, info)
VALUES
(
    'Rose Garden',
    ARRAY[13.268969332277585, 57.47291624111792],
    'A beautiful rose garden that requires regular care throughout the growing season. Regular watering and pruning needed.

**Care Instructions:**
- Water deeply 2-3 times per week
- Prune dead or diseased branches
- Fertilize monthly during growing season

![Rose Garden](https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop)'
),
(
    'Vegetable Patch',
    ARRAY[13.270514892277585, 57.47191624111792],
    'Organic vegetable garden with rotating crops. Needs regular weeding and monitoring.

**Growing Tips:**
- Practice crop rotation
- Maintain proper spacing
- Monitor soil moisture regularly'
),
(
    'Herb Garden',
    ARRAY[13.267423772277585, 57.47391624111792],
    'Mediterranean herb garden with culinary and medicinal herbs. Most herbs prefer well-draining soil.

**Herb Care:**
- Regular harvesting promotes growth
- Some herbs need winter protection
- Control spreading of invasive herbs

![Herb Garden](https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop)'
);

-- Insert sample tasks
INSERT INTO tasks (location_id, info, date_to_start, tries)
SELECT
    l.id,
    'Remove dead wood and shape bushes\nSpring pruning maintenance for the rose garden',
    NOW() - INTERVAL '2 days',
    0
FROM locations l
WHERE l.name = 'Rose Garden';

INSERT INTO tasks (location_id, info, date_to_start, date_completed, tries)
SELECT
    l.id,
    'Apply balanced rose fertilizer\nUse organic fertilizer for better results',
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '1 day',
    1
FROM locations l
WHERE l.name = 'Rose Garden';

INSERT INTO tasks (location_id, info, date_to_start, tries)
SELECT
    l.id,
    'Plant tomato seedlings\nMaintain proper spacing between plants for optimal growth',
    NOW() + INTERVAL '3 days',
    2
FROM locations l
WHERE l.name = 'Vegetable Patch';

INSERT INTO tasks (location_id, info, date_to_start, tries)
SELECT
    l.id,
    'Harvest basil before flowering\nBest flavor when harvested in the morning',
    NOW() + INTERVAL '1 day',
    0
FROM locations l
WHERE l.name = 'Herb Garden';
